In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')

###Reading_Data

In [120]:
df=pd.read_csv(r"/content/WA_Fn-UseC_-Telco-Customer-Churn.csv",encoding="latin_1")

In [121]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

###Data  Clean & Clansing

In [123]:
df.drop("customerID",axis=1,inplace=True)

In [124]:
df["TotalCharges"] = df["TotalCharges"].replace(" ", np.nan)
df['TotalCharges']=pd.to_numeric(df['TotalCharges'])

In [125]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [126]:
df["MultipleLines"].replace("No phone service","No")

0        No
1        No
2        No
3        No
4        No
5       Yes
6       Yes
7        No
8       Yes
9        No
10       No
11       No
12      Yes
13      Yes
14       No
15      Yes
16       No
17      Yes
18       No
19       No
20       No
21       No
22       No
23      Yes
24       No
25       No
26      Yes
27       No
28      Yes
29       No
30      Yes
31       No
32       No
33       No
34       No
35      Yes
36       No
37       No
38      Yes
39      Yes
40       No
41      Yes
42       No
43      Yes
44      Yes
45      Yes
46       No
47       No
48      Yes
49      Yes
50      Yes
51       No
52      Yes
53      Yes
54       No
55      Yes
56      Yes
57      Yes
58      Yes
59      Yes
60      Yes
61      Yes
62       No
63       No
64      Yes
65       No
66      Yes
67       No
68       No
69       No
70       No
71       No
72      Yes
73      Yes
74       No
75      Yes
76       No
77       No
78       No
79      Yes
80       No
81       No
82       No
83       No
84       No
85      Yes
86       No
87       No
88       No
89       No
90       No
91       No
92      Yes
93      Yes
94      Yes
95      Yes
96      Yes
97       No
98       No
99       No
100      No
101      No
102     Yes
103      No
104     Yes
105      No
106     Yes
107      No
108     Yes
109      No
110     Yes
111      No
112      No
113     Yes
114      No
115      No
116      No
117     Yes
118      No
119     Yes
120     Yes
121      No
122     Yes
123      No
124      No
125      No
126     Yes
127     Yes
128      No
129      No
130     Yes
131      No
132      No
133      No
134      No
135     Yes
136      No
137      No
138      No
139      No
140     Yes
141     Yes
142     Yes
143     Yes
144     Yes
145     Yes
146      No
147      No
148      No
149      No
150      No
151     Yes
152     Yes
153      No
154      No
155      No
156     Yes
157      No
158      No
159     Yes
160      No
161     Yes
162      No
163     Yes
164      No
165      No
166      No
167     Yes
168      No
169      No
170      No
171     Yes
172      No
173      No
174      No
175     Yes
176     Yes
177      No
178     Yes
179      No
180      No
181      No
182     Yes
183      No
184      No
185      No
186      No
187      No
188      No
189     Yes
190     Yes
191      No
192      No
193     Yes
194      No
195      No
196     Yes
197     Yes
198     Yes
199      No
200      No
201      No
202     Yes
203      No
204      No
205      No
206      No
207      No
208      No
209      No
210      No
211      No
212      No
213      No
214     Yes
215      No
216      No
217      No
218     Yes
219      No
220      No
221     Yes
222      No
223      No
224      No
225      No
226      No
227      No
228     Yes
229     Yes
230     Yes
231      No
232      No
233      No
234     Yes
235     Yes
236      No
237     Yes
238      No
239      No
240     Yes
241     Yes
242      No
243      No
244      No
245      No
246     Yes
247      No
248      No
249     Yes
250      No
251      No
252      No
253     Yes
254      No
255      No
256     Yes
257     Yes
258      No
259      No
260      No
261     Yes
262     Yes
263      No
264     Yes
265     Yes
266     Yes
267      No
268      No
269     Yes
270      No
271      No
272      No
273     Yes
274      No
275     Yes
276     Yes
277      No
278      No
279      No
280      No
281      No
282     Yes
283     Yes
284      No
285     Yes
286      No
287      No
288      No
289      No
290     Yes
291      No
292      No
293      No
294      No
295      No
296      No
297     Yes
298     Yes
299      No
300      No
301     Yes
302      No
303      No
304     Yes
305     Yes
306     Yes
307      No
308     Yes
309     Yes
310      No
311      No
312     Yes
313      No
314      No
315     Yes
316      No
317      No
318      No
319     Yes
320     Yes
321      No
322      No
323      No
324      No
325     Yes
326      No
327      No
328      No
329     Yes
330      No
331      No
332     Yes
333     Yes
334     Yes
335     Yes
336     Yes
337     Yes
338      No
339     Yes
340      No
341     Yes
342     Yes
343      No
344      No
345     Yes
346      No
347      No
348      No
349      No
350     Yes
351      No
352      No
353     Yes
354      No
355      No
356     Yes
357     Yes
358      No
359     Yes
360      No
361      No
362      No
363      No
364      No
365      No
366      No
367      No
368     Yes
369     Yes
370      No
371     Yes
372      No
373     Yes
374      No
375     Yes
376      No
377     Yes
378     Yes
379     Yes
380      No
381      No
382      No
383     Yes
384     Yes
385      No
386     Yes
387      No
388     Yes
389      No
390     Yes
391     Yes
392      No
393      No
394     Yes
395     Yes
396     Yes
397      No
398      No
399      No
400      No
401      No
402     Yes
403      No
404      No
405      No
406     Yes
407      No
408      No
409      No
410     Yes
411     Yes
412     Yes
413     Yes
414      No
415      No
416     Yes
417     Yes
418      No
419      No
420     Yes
421      No
422     Yes
423     Yes
424      No
425     Yes
426     Yes
427     Yes
428     Yes
429     Yes
430      No
431      No
432      No
433      No
434      No
435      No
436      No
437     Yes
438     Yes
439      No
440     Yes
441     Yes
442     Yes
443     Yes
444      No
445     Yes
446      No
447     Yes
448      No
449      No
450     Yes
451      No
452      No
453      No
454     Yes
455     Yes
456      No
457      No
458      No
459     Yes
460      No
461      No
462     Yes
463     Yes
464     Yes
465      No
466     Yes
467     Yes
468      No
469      No
470      No
471      No
472      No
473      No
474      No
475     Yes
476      No
477      No
478      No
479      No
480      No
481      No
482      No
483     Yes
484      No
485     Yes
486     Yes
487     Yes
488      No
489     Yes
490     Yes
491      No
492      No
493     Yes
494      No
495      No
496      No
497      No
498      No
499     Yes
500     Yes
501     Yes
502     Yes
503      No
504     Yes
505     Yes
506     Yes
507      No
508     Yes
509      No
510      No
511     Yes
512     Yes
513     Yes
514     Yes
515     Yes
516      No
517      No
518      No
519      No
520     Yes
521     Yes
522     Yes
523     Yes
524     Yes
525      No
526     Yes
527     Yes
528      No
529     Yes
530      No
531      No
532      No
533     Yes
534     Yes
535     Yes
536     Yes
537      No
538      No
539      No
540     Yes
541     Yes
542      No
543     Yes
544      No
545      No
546      No
547     Yes
548     Yes
549      No
550     Yes
551     Yes
552      No
553     Yes
554     Yes
555     Yes
556      No
557      No
558      No
559      No
560     Yes
561     Yes
562      No
563     Yes
564      No
565      No
566      No
567     Yes
568     Yes
569      No
570      No
571     Yes
572      No
573     Yes
574     Yes
575      No
576     Yes
577      No
578     Yes
579      No
580      No
581      No
582     Yes
583      No
584      No
585     Yes
586      No
587      No
588     Yes
589     Yes
590     Yes
591     Yes
592     Yes
593      No
594      No
595     Yes
596      No
597     Yes
598     Yes
599      No
600      No
601      No
602     Yes
603     Yes
604     Yes
605     Yes
606      No
607      No
608     Yes
609     Yes
610      No
611      No
612      No
613     Yes
614     Yes
615     Yes
616      No
617     Yes
618     Yes
619     Yes
620      No
621     Yes
622      No
623      No
624      No
625      No
626     Yes
627     Yes
628     Yes
629     Yes
630     Yes
631     Yes
632     Yes
633      No
634      No
635     Yes
636      No
637     Yes
638     Yes
639     Yes
640     Yes
641      No
642      No
643      No
644     Yes
645     Yes
646      No
647     Yes
648     Yes
649      No
650      No
651      No
652      No
653     Yes
654      No
655      No
656     Yes
657      No
658      No
659      No
660      No
661      No
662      No
663     Yes
664      No
665      No
666      No
667      No
668      No
669      No
670      No
671     Yes
672     Yes
673     Yes
674      No
675     Yes
676     Yes
677      No
678     Yes
679     Yes
680      No
681      No
682      No
683     Yes
684      No
685      No
686     Yes
687      No
688      No
689     Yes
690      No
691     Yes
692      No
693     Yes
694      No
695      No
696     Yes
697      No
698      No
699     Yes
700     Yes
701     Yes
702     Yes
703      No
704      No
705      No
706      No
707     Yes
708      No
709     Yes
710      No
711      No
712     Yes
713     Yes
714     Yes
715     Yes
716      No
717     Yes
718      No
719     Yes
720      No
721      No
722     Yes
723      No
724     Yes
725      No
726     Yes
727      No
728     Yes
729     Yes
730     Yes
731      No
732      No
733     Yes
734     Yes
735      No
736     Yes
737      No
738     Yes
739     Yes
740     Yes
741      No
742     Yes
743     Yes
744      No
745     Yes
746     Yes
747      No
748      No
749      No
750      No
751      No
752      No
753      No
754      No
755     Yes
756      No
757      No
758      No
759     Yes
760      No
761      No
762      No
763     Yes
764      No
765      No
766     Yes
767      No
768      No
769      No
770      No
771     Yes
772      No
773      No
774      No
775     Yes
776      No
777     Yes
778     Yes
779      No
780      No
781      No
782      No
783      No
784      No
785     Yes
786     Yes
787     Yes
788     Yes
789     Yes
790      No
791     Yes
792      No
793      No
794      No
795      No
796     Yes
797     Yes
798      No
799     Yes
800     Yes
801     Yes
802     Yes
803      No
804      No
805     Yes
806      No
807     Yes
808     Yes
809      No
810     Yes
811     Yes
812     Yes
813      No
814      No
815     Yes
816      No
817      No
818     Yes
819     Yes
820     Yes
821      No
822     Yes
823      No
824     Yes
825      No
826     Yes
827     Yes
828      No
829      No
830     Yes
831     Yes
832      No
833     Yes
834      No
835     Yes
836      No
837      No
838      No
839      No
840     Yes
841     Yes
842      No
843      No
844      No
845      No
846      No
847      No
848     Yes
849     Yes
850     Yes
851     Yes
852     Yes
853      No
854      No
855     Yes
856     Yes
857      No
858     Yes
859      No
860      No
861     Yes
862      No
863      No
864     Yes
865      No
866      No
867      No
868     Yes
869     Yes
870     Yes
871      No
872      No
873      No
874     Yes
875      No
876      No
877      No
878     Yes
879     Yes
880      No
881      No
882      No
883     Yes
884      No
885      No
886      No
887     Yes
888      No
889     Yes
890     Yes
891     Yes
892     Yes
893      No
894     Yes
895     Yes
896     Yes
897     Yes
898      No
899     Yes
900      No
901     Yes
902      No
903      No
904      No
905     Yes
906      No
907      No
908      No
909     Yes
910      No
911     Yes
912     Yes
913      No
914     Yes
915     Yes
916      No
917      No
918     Yes
919      No
920     Yes
921      No
922     Yes
923     Yes
924      No
925      No
926     Yes
927      No
928     Yes
929      No
930      No
931      No
932      No
933     Yes
934      No
935     Yes
936      No
937     Yes
938     Yes
939      No
940      No
941      No
942      No
943      No
944     Yes
945     Yes
946      No
947     Yes
948     Yes
949      No
950      No
951      No
952      No
953      No
954     Yes
955      No
956     Yes
957      No
958     Yes
959      No
960      No
961      No
962      No
963     Yes
964      No
965      No
966      No
967      No
968      No
969     Yes
970      No
971     Yes
972      No
973      No
974      No
975     Yes
976      No
977     Yes
978     Yes
979      No
980      No
981      No
982      No
983     Yes
984     Yes
985     Yes
986      No
987      No
988      No
989      No
990      No
991     Yes
992     Yes
993     Yes
994      No
995     Yes
996      No
997     Yes
998      No
999      No
1000     No
1001    Yes
1002     No
1003     No
1004     No
1005    Yes
1006    Yes
1007     No
1008    Yes
1009     No
1010     No
1011     No
1012     No
1013     No
1014     No
1015     No
1016    Yes
1017    Yes
1018     No
1019     No
1020     No
1021     No
1022     No
1023     No
1024     No
1025     No
1026    Yes
1027    Yes
1028    Yes
1029     No
1030     No
1031    Yes
1032     No
1033    Yes
1034     No
1035    Yes
1036    Yes
1037     No
1038     No
1039     No
1040     No
1041     No
1042     No
1043     No
1044     No
1045    Yes
1046    Yes
1047     No
1048     No
1049     No
1050     No
1051     No
1052    Yes
1053     No
1054    Yes
1055     No
1056     No
1057     No
1058     No
1059    Yes
1060     No
1061    Yes
1062     No
1063     No
1064     No
1065    Yes
1066     No
1067     No
1068    Yes
1069     No
1070     No
1071     No
1072     No
1073    Yes
1074     No
1075    Yes
1076    Yes
1077    Yes
1078    Yes
1079     No
1080     No
1081    Yes
1082    Yes
1083     No
1084     No
1085     No
1086     No
1087    Yes
1088    Yes
1089    Yes
1090    Yes
1091     No
1092     No
1093    Yes
1094    Yes
1095     No
1096     No
1097     No
1098    Yes
1099    Yes
1100    Yes
1101     No
1102     No
1103    Yes
1104     No
1105     No
1106    Yes
1107    Yes
1108    Yes
1109     No
1110     No
1111     No
1112    Yes
1113    Yes
1114    Yes
1115    Yes
1116    Yes
1117    Yes
1118    Yes
1119     No
1120     No
1121    Yes
1122     No
1123     No
1124     No
1125    Yes
1126     No
1127     No
1128     No
1129    Yes
1130     No
1131    Yes
1132    Yes
1133     No
1134     No
1135    Yes
1136     No
1137     No
1138    Yes
1139     No
1140    Yes
1141     No
1142    Yes
1143    Yes
1144     No
1145     No
1146     No
1147    Yes
1148    Yes
1149     No
1150     No
1151     No
1152     No
1153     No
1154    Yes
1155    Yes
1156     No
1157    Yes
1158    Yes
1159     No
1160     No
1161     No
1162     No
1163    Yes
1164    Yes
1165     No
1166    Yes
1167    Yes
1168     No
1169     No
1170    Yes
1171     No
1172    Yes
1173     No
1174    Yes
1175    Yes
1176    Yes
1177    Yes
1178     No
1179    Yes
1180     No
1181     No
1182     No
1183     No
1184     No
1185    Yes
1186    Yes
1187    Yes
1188     No
1189     No
1190    Yes
1191    Yes
1192    Yes
1193     No
1194     No
1195     No
1196    Yes
1197     No
1198     No
1199    Yes
1200    Yes
1201     No
1202     No
1203    Yes
1204     No
1205    Yes
1206     No
1207     No
1208     No
1209    Yes
1210     No
1211    Yes
1212     No
1213     No
1214    Yes
1215     No
1216     No
1217    Yes
1218    Yes
1219    Yes
1220    Yes
1221     No
1222     No
1223    Yes
1224     No
1225     No
1226    Yes
1227    Yes
1228    Yes
1229    Yes
1230    Yes
1231     No
1232     No
1233    Yes
1234     No
1235    Yes
1236    Yes
1237     No
1238    Yes
1239     No
1240     No
1241    Yes
1242     No
1243     No
1244     No
1245     No
1246    Yes
1247    Yes
1248    Yes
1249     No
1250    Yes
1251     No
1252     No
1253     No
1254     No
1255     No
1256    Yes
1257     No
1258     No
1259     No
1260     No
1261     No
1262     No
1263    Yes
1264     No
1265     No
1266    Yes
1267    Yes
1268    Yes
1269    Yes
1270    Yes
1271     No
1272     No
1273    Yes
1274    Yes
1275     No
1276     No
1277     No
1278     No
1279     No
1280    Yes
1281     No
1282     No
1283    Yes
1284     No
1285     No
1286     No
1287    Yes
1288     No
1289    Yes
1290    Yes
1291     No
1292    Yes
1293    Yes
1294     No
1295    Yes
1296     No
1297    Yes
1298     No
1299     No
1300    Yes
1301     No
1302     No
1303     No
1304    Yes
1305     No
1306    Yes
1307     No
1308    Yes
1309    Yes
1310    Yes
1311     No
1312    Yes
1313    Yes
1314    Yes
1315     No
1316     No
1317    Yes
1318     No
1319     No
1320     No
1321     No
1322     No
1323    Yes
1324     No
1325     No
1326     No
1327    Yes
1328     No
1329     No
1330     No
1331     No
1332    Yes
1333     No
1334     No
1335     No
1336     No
1337     No
1338     No
1339    Yes
1340     No
1341     No
1342     No
1343     No
1344     No
1345    Yes
1346    Yes
1347     No
1348     No
1349     No
1350    Yes
1351     No
1352     No
1353     No
1354    Yes
1355     No
1356    Yes
1357    Yes
1358     No
1359    Yes
1360    Yes
1361    Yes
1362     No
1363    Yes
1364     No
1365     No
1366    Yes
1367    Yes
1368     No
1369    Yes
1370     No
1371     No
1372     No
1373     No
1374     No
1375     No
1376     No
1377    Yes
1378    Yes
1379     No
1380     No
1381     No
1382    Yes
1383    Yes
1384     No
1385     No
1386    Yes
1387    Yes
1388     No
1389    Yes
1390     No
1391    Yes
1392     No
1393     No
1394    Yes
1395    Yes
1396    Yes
1397     No
1398    Yes
1399     No
1400     No
1401     No
1402     No
1403     No
1404    Yes
1405    Yes
1406    Yes
1407     No
1408    Yes
1409    Yes
1410    Yes
1411     No
1412     No
1413    Yes
1414    Yes
1415     No
1416     No
1417     No
1418    Yes
1419     No
1420    Yes
1421    Yes
1422    Yes
1423    Yes
1424     No
1425     No
1426    Yes
1427     No
1428    Yes
1429    Yes
1430    Yes
1431    Yes
1432     No
1433     No
1434    Yes
1435    Yes
1436    Yes
1437    Yes
1438     No
1439     No
1440     No
1441    Yes
1442     No
1443     No
1444     No
1445    Yes
1446    Yes
1447    Yes
1448     No
1449     No
1450     No
1451    Yes
1452     No
1453     No
1454     No
1455    Yes
1456    Yes
1457    Yes
1458     No
1459     No
1460    Yes
1461    Yes
1462     No
1463     No
1464     No
1465     No
1466     No
1467    Yes
1468    Yes
1469    Yes
1470     No
1471    Yes
1472    Yes
1473    Yes
1474    Yes
1475    Yes
1476     No
1477    Yes
1478    Yes
1479     No
1480     No
1481     No
1482     No
1483     No
1484     No
1485    Yes
1486     No
1487    Yes
1488     No
1489     No
1490    Yes
1491     No
1492    Yes
1493     No
1494     No
1495    Yes
1496     No
1497     No
1498    Yes
1499    Yes
1500     No
1501     No
1502    Yes
1503    Yes
1504     No
1505    Yes
1506     No
1507     No
1508     No
1509     No
1510    Yes
1511     No
1512    Yes
1513     No
1514     No
1515    Yes
1516    Yes
1517    Yes
1518     No
1519     No
1520     No
1521    Yes
1522     No
1523     No
1524    Yes
1525     No
1526     No
1527     No
1528     No
1529     No
1530     No
1531    Yes
1532     No
1533     No
1534     No
1535    Yes
1536     No
1537    Yes
1538    Yes
1539     No
1540     No
1541     No
1542     No
1543     No
1544     No
1545    Yes
1546     No
1547    Yes
1548     No
1549     No
1550    Yes
1551    Yes
1552    Yes
1553     No
1554     No
1555     No
1556     No
1557    Yes
1558    Yes
1559     No
1560     No
1561    Yes
1562     No
1563     No
1564    Yes
1565     No
1566     No
1567     No
1568    Yes
1569     No
1570     No
1571     No
1572     No
1573     No
1574     No
1575     No
1576     No
1577     No
1578     No
1579     No
1580    Yes
1581     No
1582    Yes
1583    Yes
1584     No
1585    Yes
1586    Yes
1587    Yes
1588    Yes
1589     No
1590     No
1591     No
1592     No
1593     No
1594    Yes
1595     No
1596     No
1597    Yes
1598     No
1599     No
1600    Yes
1601    Yes
1602     No
1603    Yes
1604    Yes
1605     No
1606     No
1607     No
1608     No
1609    Yes
1610     No
1611    Yes
1612    Yes
1613     No
1614     No
1615     No
1616     No
1617    Yes
1618     No
1619    Yes
1620     No
1621    Yes
1622     No
1623    Yes
1624    Yes
1625     No
1626    Yes
1627     No
1628    Yes
1629     No
1630    Yes
1631    Yes
1632    Yes
1633     No
1634     No
1635     No
1636    Yes
1637     No
1638    Yes
1639     No
1640     No
1641    Yes
1642     No
1643     No
1644    Yes
1645    Yes
1646    Yes
1647     No
1648    Yes
1649     No
1650    Yes
1651     No
1652     No
1653     No
1654     No
1655     No
1656    Yes
1657    Yes
1658    Yes
1659    Yes
1660    Yes
1661    Yes
1662     No
1663    Yes
1664    Yes
1665    Yes

In [127]:
tran=["Partner","Dependents","PhoneService","MultipleLines","OnlineSecurity","OnlineBackup","TechSupport","StreamingTV","StreamingMovies","PaperlessBilling","Churn","DeviceProtection"]
for col in tran:
  df[col]=df[col].map({"Yes":1,"No":0})

In [128]:
df.dtypes

gender               object
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines       float64
InternetService      object
OnlineSecurity      float64
OnlineBackup        float64
DeviceProtection    float64
TechSupport         float64
StreamingTV         float64
StreamingMovies     float64
Contract             object
PaperlessBilling      int64
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

###split input & output

In [129]:
input = df.drop("Churn",axis=1)
ouput = df["Churn"]

###Train and Test For Data

In [130]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(input,ouput,test_size=0.2,random_state=42)

###Pipeline & OneHotEncoding & Simpleimuter

In [131]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy="median")
pr_data=Pipeline(steps=[("imputer",si)])
X_train[["TotalCharges"]]=si.fit_transform(X_train[["TotalCharges"]])
pr_data

Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))])

In [149]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
col =["tenure","MonthlyCharges","TotalCharges"]
X_train[col]=ss.fit_transform(X_train[col])
X_test[col]=ss.transform(X_test[col])
num_data=Pipeline(steps=[("pr_data",SimpleImputer()),("scaler",ss)])
num_data

Pipeline(steps=[('pr_data', SimpleImputer()), ('scaler', StandardScaler())])

In [150]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop="first", handle_unknown="ignore")
cat_data = Pipeline(steps=[("onehotEncoder", ohe)])
cols = ["gender", "Contract", "InternetService", "PaymentMethod"]
X_train_encoded = categ_data.fit_transform(X_train[cols])
X_test_encoded = categ_data.transform(X_test[cols])

cat_data

Pipeline(steps=[('onehotEncoder',
                 OneHotEncoder(drop='first', handle_unknown='ignore'))])

In [154]:
from sklearn.compose import ColumnTransformer
pre_pepline=ColumnTransformer(transformers=[("num",num_data,col),("cat",cat_data,cols)])
pre_pepline

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('pr_data', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['tenure', 'MonthlyCharges', 'TotalCharges']),
                                ('cat',
                                 Pipeline(steps=[('onehotEncoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'))]),
                                 ['gender', 'Contract', 'InternetService',
                                  'PaymentMethod'])])

###ML

In [135]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train_encoded,y_train)

LogisticRegression()

In [136]:
y_test_pred=lr.predict(X_test_encoded)
y_test_pred

array([0, 0, 0, ..., 0, 0, 0])

In [137]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_test_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

0.7906316536550745
[[928 108]
 [187 186]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1036
           1       0.63      0.50      0.56       373

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [138]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
dt=DecisionTreeClassifier()
para_grid={"max_depth":np.arange(3,10),"min_samples_split":range(2,15),"criterion":["gini","entropy"]}
dt_cv=(GridSearchCV(dt,para_grid,cv=5))
dt_cv.fit(X_train_encoded,y_train)
dt_pred=dt_cv.predict(X_test_encoded)

In [139]:
print(dt_cv.best_score_,dt_cv.best_params_)

0.7701458311334417 {'criterion': 'gini', 'max_depth': np.int64(4), 'min_samples_split': 2}

In [140]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,dt_pred))
print(confusion_matrix(y_test,dt_pred))
print(classification_report(y_test,dt_pred))

0.7849538679914834
[[933 103]
 [200 173]]
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1036
           1       0.63      0.46      0.53       373

    accuracy                           0.78      1409
   macro avg       0.73      0.68      0.70      1409
weighted avg       0.77      0.78      0.77      1409

In [141]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
para_grid={"max_depth":np.arange(3,10),"n_estimators":range(10,25)}
rf_cv=(GridSearchCV(rf,para_grid,cv=5))
rf_cv.fit(X_train_encoded,y_train)
rf_pred=rf_cv.predict(X_test_encoded)

In [142]:
print(rf_cv.best_score_,rf_cv.best_params_)

0.7712115504940101 {'max_depth': np.int64(7), 'n_estimators': 17}

In [143]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,rf_pred))
print(confusion_matrix(y_test,rf_pred))
print(classification_report(y_test,rf_pred))

0.7906316536550745
[[928 108]
 [187 186]]
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1036
           1       0.63      0.50      0.56       373

    accuracy                           0.79      1409
   macro avg       0.73      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [144]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
param_grid={'n_neighbors':np.arange(1,10)}
knn_cv=GridSearchCV(knn,param_grid,cv=5)
knn_cv.fit(X_train_encoded,y_train)
yk_pred=knn_cv.predict(X_test_encoded)

In [145]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,yk_pred))
print(confusion_matrix(y_test,yk_pred))
print(classification_report(y_test,yk_pred))

0.772888573456352
[[986  50]
 [270 103]]
              precision    recall  f1-score   support

           0       0.79      0.95      0.86      1036
           1       0.67      0.28      0.39       373

    accuracy                           0.77      1409
   macro avg       0.73      0.61      0.63      1409
weighted avg       0.76      0.77      0.74      1409

In [155]:
final_pipeline=Pipeline(steps=[("pre_pepline",pre_pepline),("lr",LogisticRegression())])
final_pipeline

Pipeline(steps=[('pre_pepline',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('pr_data',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehotEncoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['gender', 'Contract',
                                                   'InternetService',
                                                   'PaymentMethod'])])),
                ('lr', LogisticRegression())])

In [156]:
final_pipeline.fit(X_train,y_train)

Pipeline(steps=[('pre_pepline',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('pr_data',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['tenure', 'MonthlyCharges',
                                                   'TotalCharges']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehotEncoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  ['gender', 'Contract',
                                                   'InternetService',
                                                   'PaymentMethod'])])),
                ('lr', LogisticRegression())])

In [158]:
y_pred = final_pipeline.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [160]:
print('evaluation on training \n', classification_report(y_train, final_pipeline.predict(X_train)))
print('evaluation on testing \n', classification_report(y_test, y_pred))

evaluation on training
               precision    recall  f1-score   support

           0       0.84      0.89      0.86      4138
           1       0.64      0.52      0.57      1496

    accuracy                           0.79      5634
   macro avg       0.74      0.71      0.72      5634
weighted avg       0.78      0.79      0.79      5634

evaluation on testing
               precision    recall  f1-score   support

           0       0.85      0.90      0.88      1036
           1       0.67      0.56      0.61       373

    accuracy                           0.81      1409
   macro avg       0.76      0.73      0.74      1409
weighted avg       0.80      0.81      0.81      1409

In [161]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.8119233498935415

In [162]:
import joblib
joblib.dump(final_pipeline,'final_model.pkl')

['final_model.pkl']

In [163]:
model = joblib.load("final_model.pkl")

In [164]:
model.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0])